ChainSafe/PINT

- Cargo.lock
- pallets/asset-depository/Cargo.toml
- pallets/asset-depository/README.md
- pallets/asset-depository/src/lib.rs
- pallets/asset-depository/src/mock.rs
- pallets/asset-depository/src/tests.rs
- pallets/asset-depository/src/traits.rs
- pallets/asset-depository/src/types.rs
- Adds an additional palette which sole purpose is to track asset balances for a user
- It's abstracted via the `MultiAssetDepository` trait, which is intended to be included in the asset transaction routine for depositing and withdrawing funds on a cross-chain message issued by a user
```
cargo test
```
- Adds the necessary depository functionality for #25 in order to deposit cross chain assets https://github.com/ChainSafe/PINT/issues/25#issuecomment-824926629 to temporarily store them before converting them to PINT or withdrawing them via XCM upon a user request
> feat: add asset depository pallet

- .circleci/config.yml
* Remove verbose prefetch-cache job
* Cache binaries: 
* cargo-audit
* sccache
* Share cache to `security` job directly
> Add sccache

- .circleci/config.yml
This is really a small fix, I can embed this into my next PR or @mattsse doesn't mind adding this fix to your pending PRs?
Forgot to ignore all branches in my last PR #49, and here is the doc of CircieCI tag trigger, [Executing workflows for a git tag](https://circleci.com/docs/2.0/workflows/#executing-workflows-for-a-git-tag)
* [clearloop/PINT](https://github.com/clearloop/pint) ( still building now )
Tested on my private repo, [echo-when-tag](https://app.circleci.com/pipelines/github/clearloop/cydonia/7/workflows/874a3444-dfc7-4c7e-ab1b-efe0c0cdf2fd/jobs/8), it would be nice downloading the testing  [config.yml](https://github.com/clearloop/cydonia/blob/master/.circleci/config.yml) or merge this branch into a personal fork of PINT to test this instruction
---
BTW, can anybody delete …
> ci(docker): hotfix the trigger of publishing docker images by tags

- node/src/chain_spec.rs
- pallets/committee/src/benchmarking.rs
- pallets/committee/src/lib.rs
- pallets/committee/src/mock.rs
- pallets/committee/src/tests.rs
- pallets/committee/src/types.rs
- runtime/src/lib.rs
> feat(committee): add CommitteeMember origin for pallet committee

- pallets/asset-index/src/lib.rs
- pallets/asset-index/src/mock.rs
- pallets/asset-index/src/tests.rs
- pallets/price-feed/src/lib.rs
- pallets/price-feed/src/traits.rs
```
CI
```
Ref #105 
Closes #93 
Closes #94 
Closes #95
> feat(asset-index): store initial price pair

- Cargo.lock
- pallets/asset-index/Cargo.toml
- pallets/asset-index/src/lib.rs
- pallets/asset-index/src/traits.rs
- pallets/asset-index/src/types.rs
- pallets/remote-asset-manager/Cargo.toml
- pallets/remote-asset-manager/src/lib.rs
- pallets/remote-asset-manager/src/traits.rs
- primitives/primitives/Cargo.toml
- primitives/primitives/README.md
- primitives/primitives/src/lib.rs
- primitives/primitives/src/traits.rs
- runtime/Cargo.toml
- runtime/src/lib.rs
- Creates a new primtives crate for shared types/traits
- move the `MultiAssetRegistry` that is used by both the asset-index and remote-asset-manager
-
```
```
- Ref #116
> refactor: extract asset registry to new primitives crate

- Cargo.lock
- pallets/remote-asset-manager/Cargo.toml
- pallets/remote-asset-manager/src/lib.rs
- primitives/xcm-calls/src/staking.rs
- runtime/src/lib.rs
- introduce the `MinimumRemoteStashBalance` type which is essentially a map (AssetId -> Balance) that determines the minimum amount of balance of a xcm asset should be kept in stash (unbonded) at all times.
- This must be at least the ExistentialDeposit as configured on the asset's native chain (e.g. DOT/Polkadot)
- This will restrict the amount the council can stake
- This will restrict asset withdrawals from PINT (xcm transfers) if the updated stash balance (of the PINT's parachain account) would fall below the configured threshold.
Note: 
* this does not prevent the user from redeeming PINT for assets, but potentially restricts withdrawals from PINT -> parachain/relaychain until the stash exceeds the threshold again.
* it is assumed that the total issuance/total balance of an asset …
> feat: optimise xcm asst management and monitor balances 

- .circleci/config.yml
- docker/launch.Dockerfile
- js/e2e/src/launch.ts
- js/e2e/src/runner.ts
- js/finalize/index.ts
- js/finalize/package.json
- js/finalize/tsconfig.json
- js/package.json
- js/yarn.lock
Add package finalize and do it in CI
```
CI
```
Closes #86
> Test PINT finalization in CI

- Cargo.lock
- pallets/asset-index/src/lib.rs
- pallets/asset-index/src/tests.rs
- pallets/asset-index/src/traits.rs
- pallets/saft-registry/Cargo.toml
- pallets/saft-registry/src/lib.rs
- pallets/saft-registry/src/mock.rs
- pallets/saft-registry/src/tests.rs
- extend the `AssetRecorder` trait with a standalone `set_availiabiliy` function 
- add designated support for `add_saft` that directly mints SAFT and PINT and fails if AssetId is liquid.
- update some tests.
```
```
- Closes #162
> feat: extend asset recorder trait

- pallets/asset-index/src/benchmarking.rs
- pallets/asset-index/src/lib.rs
- pallets/asset-index/src/tests.rs
- pallets/asset-index/src/traits.rs
- pallets/remote-asset-manager/src/lib.rs
- pallets/saft-registry/Cargo.toml
- pallets/saft-registry/src/lib.rs
- pallets/saft-registry/src/mock.rs
- pallets/saft-registry/src/tests.rs
- runtime/src/lib.rs
- Add `remove_asset` extrinsic and update trait abstraction
- SAFTs are burned, liquids are transfered (from the treasury account)
Revive of #73
```
```
- Closes #24 #2
> feat: implement remove asset

- runtime/src/lib.rs
This is for easy debugging, in case of the conversion of XCM error is tricky, we can transform the XCM Error into `DispatchError` by hand, for example
```rust
DispatchError::Module {
module,
index,
message,
}
```
```
CI
```
- #186
> feat(runtime): add indices of pallets in runtime

- pallets/asset-index/src/lib.rs
- pallets/asset-index/src/traits.rs
- Adds another extrinsic to register new assets
We could also think about dropping the `location` parameter of the `add_asset` in favor of this new extrinsic?
```
```
- Closes #179
> feat: add register asset extrinsic

- js/e2e/index.ts
XCM transfer failed because the codec of the arguments of `add_asset`
```
CI
```
Closes #176
> ci(e2e): fix the arguments of add_asset in e2e test

- pallets/asset-index/src/lib.rs
- pallets/asset-index/src/mock.rs
- pallets/asset-index/src/tests.rs
- pallets/saft-registry/src/mock.rs
- pallets/saft-registry/src/tests.rs
- runtime/src/lib.rs
- Ensures the given asset is not the native asset for operations that expect liquid / saft
This would probably be caught as well by the `ensure_liquid_asset` function but this way it's handled explicitly.
```
```
- Closes #191
> fix: disallow native asset deposits and withdrawals

- pallets/asset-index/src/lib.rs
- use `amount` instead of `value` in `add_asset`
- use `units` instead of `amount` in `deposit`
```
CI
```
-
> perf(asset-index): explicit arguments of add_asset and deposit

- pallets/asset-index/src/lib.rs
Use `Price::checked_from_rational` instead of `Price::from_inner`, use u128 turns into Price(0)
```
CI
```
-
> fix(asset-index): correct the calculation of initial price

- Cargo.lock
- pallets/committee/Cargo.toml
- pallets/committee/src/mock.rs
- pallets/committee/src/tests.rs
- pallets/committee/src/types.rs
- pallets/remote-asset-manager/Cargo.toml
Could not build with `cargo build --release` because of using `runtime-features` directly in `Cargo.toml`
```
CI
```
Closes #208
> fix(remote-asset-manager): the usages of runtime-benchmarks feature

- pallets/asset-index/src/lib.rs
- pallets/asset-index/src/mock.rs
- pallets/remote-asset-manager/src/mock.rs
- pallets/saft-registry/src/mock.rs
- primitives/primitives/src/lib.rs
- resources/types.json
- runtime/src/lib.rs
- Adds a fixed fee type for withdrawals, from there the final fee should be a configurable function based on the time the assets remained in the index but this needs some further work on how deposits are tracked first.
```
```
- Closes #206
> refactor: withdrawal fee model

- pallets/asset-index/src/lib.rs
- pallets/asset-index/src/mock.rs
- pallets/asset-index/src/tests.rs
- pallets/asset-index/src/types.rs
- pallets/remote-asset-manager/src/mock.rs
- pallets/saft-registry/src/mock.rs
- runtime/src/lib.rs
- tracks minted index tokens (deposits) so that the `LockupPeriod` can be enforced
- add `unlock` extrinsic to manually unlock index tokens
```
```
- Closes #212
> feat: lock freshly minted index token up for lockup period

- pallets/asset-index/src/lib.rs
- pallets/asset-index/src/mock.rs
- pallets/asset-index/src/tests.rs
- pallets/asset-index/src/types.rs
- drop unused adapter types that was replaced with `orml_currency` and `orml_xtokens`
-
> chore: rm unused adapter types

- pallets/asset-index/src/lib.rs
- pallets/asset-index/src/types.rs
- Split the rather complex `withdraw` dispatchable into separate helper functions and introduce more types. This will come in handy once we add rpc support that provides asset distributions
```
```
- Ref #205
> refactor: split asset withdraw calculation to separate functions

- pallets/asset-index/src/lib.rs
- primitives/primitives/src/traits.rs
- Introduce `NavProvider` that abstracts all NAV calculations and explains all terminology and formula
- Fixes some soundness issues when performing NAV calculations
The `NavProvider` comes with dedicated functions for `SAFT`, `liquid` and `index token`, perhaps it makes sense to further split that?
```
```
- Closes #248 
- Follow up #250
> feat: abstract all NAV related calculations over NavProvider trait

- pallets/asset-index/src/lib.rs
- pallets/asset-index/src/types.rs
- This simplifies the state mache for redemption, basically letting the remote asset manager do all the work after #244 
```
```
- Closes #263
> feat: simplify redemption statemachine

- pallets/asset-index/src/lib.rs
- pallets/asset-index/src/mock.rs
- pallets/remote-asset-manager/src/lib.rs
- pallets/remote-asset-manager/src/mock.rs
- pallets/remote-asset-manager/src/tests.rs
- pallets/remote-asset-manager/src/traits.rs
- pallets/remote-asset-manager/src/types.rs
- pallets/saft-registry/src/mock.rs
- primitives/primitives/src/traits.rs
- runtime/common/src/constants.rs
- runtime/dev/src/lib.rs
- runtime/kusama/src/lib.rs
- runtime/polkadot/src/lib.rs
- This handles xcm staking related calls on a per block basis, rather than on a per deposit/withdrawal basis
- upon block initialization we check whether we need to dispatch a xcm which should succeed because we expect only valid assets to be available for staking. The fees for the weight should be paid for by the LP upon deposit/withdrawal where worst case is 1 deposit /withdrawal is 1 XCM.
This requires some additional work regarding automated rebond/withdraw and still leaves some room for simplifications with the existing xcm extrinsics, which I'll follow up on a new PR. As well as advanced testing.
```
```
- Closes #244
> feat: handle xcm staking calls on a per block basis

- pallets/asset-index/src/lib.rs
- runtime/common/src/lib.rs
- runtime/common/src/types.rs
- runtime/dev/src/lib.rs
- runtime/kusama/src/lib.rs
- runtime/polkadot/src/lib.rs
```
CI
```
- #301 
- Closes #268
> feat(runtime): checking and renaming origins for all pallets

- pallets/asset-index/Cargo.toml
- pallets/asset-index/src/benchmarking.rs
- pallets/asset-index/src/lib.rs
- pallets/price-feed/Cargo.toml
- pallets/price-feed/src/benchmarking.rs
- pallets/price-feed/src/lib.rs
- pallets/price-feed/src/mock.rs
- pallets/remote-asset-manager/Cargo.toml
- pallets/remote-asset-manager/src/lib.rs
- pallets/saft-registry/Cargo.toml
- pallets/saft-registry/src/benchmarking.rs
- pallets/saft-registry/src/lib.rs
- primitives/primitives/Cargo.toml
- primitives/primitives/src/traits.rs
- primitives/primitives/src/types.rs
- runtime/dev/Cargo.toml
- runtime/kusama/Cargo.toml
- runtime/polkadot/Cargo.toml
- Use a feature gated trait to create AssetIds in runtime benchmarks
```
```
- Closes #310
> feat: add MaybeAssetIdConvert trait for runtime benchmarks

- js/e2e/index.ts
- js/e2e/src/extrinsic.ts
- Fixed the VotingPeriod calculation of pallet committee
- Fund committee members from start
- Pend errors of verification without panic
TXs in `assetIndex`, `saftRegistry` and `remoteAssetManager` are broken because of #305 , should be fixed after #324 
```
CI
```
-
> feat(e2e): fix pallet asset-index and committee in e2e tests

- pallets/asset-index/src/lib.rs
- pallets/saft-registry/src/lib.rs
> feat: add root calls

- js/e2e/index.ts
- js/e2e/src/config.ts
- js/e2e/src/extrinsic.ts
- js/e2e/src/runner.ts
- js/pint-types-bundle/index.ts
- runtime/dev/src/lib.rs
```
CI
```
- Closes #281 
- Closes #301
> feat(e2e): apply admin origin to e2e tests

- runtime/dev/src/lib.rs
- runtime/kusama/src/lib.rs
- runtime/polkadot/src/lib.rs
Use `EnsureMember` for submission origin
---
Confusing about replacing signed origin: most of the calls of PINT requires `GovernanceOrigin` or `Member`, so what exactly people which are not of a member of the committee can do in PINT?
```
```
- Closes #367
> feat(committee): only members can submit proposals

- js/e2e/index.ts
- pallets/asset-index/src/benchmarking.rs
- pallets/asset-index/src/lib.rs
- pallets/asset-index/src/tests.rs
- pallets/remote-asset-manager/src/tests.rs
- pallets/saft-registry/src/mock.rs
- clean add asset
- updates tests
- updates benchmarks
- updates e2e tests
```
```
- Closes #383 
- Closes #369
> feat(asset-index): split off add_asset

- pallets/asset-index/src/lib.rs
- pallets/saft-registry/src/lib.rs
- primitives/primitives/src/traits.rs
> chore: remove uneccessary clones

- pallets/asset-index/src/lib.rs
- pallets/asset-index/src/mock.rs
- pallets/asset-index/src/tests.rs
- The question raised in #414 can only happen if the caller account does not exist yet and the given nav is below ED, this is unlikely to happen, but if it does it is to the disadvantage of the caller. 
- The regular `deposit` call ensures that the pint amount is within a certain range which prevents the ED edge case entirely.
```
```
- Closes #414
> chore: document ED behaviour in add asset and saft
