Cargo.lock
pallets/asset-index/src/lib.rs
pallets/asset-index/src/mock.rs
pallets/asset-index/src/tests.rs
pallets/asset-index/src/types.rs
pallets/remote-asset-manager/src/lib.rs
pallets/remote-asset-manager/src/traits.rs
runtime/src/lib.rs

- Implements the `withdraw` extrinsic
- Only liquid assets are considered when calculating the distribution
```
cargo test
```
- Closes #26

feat(index): implement withdraw extrinsic

---

js/e2e/src/runner.ts
js/pint-types-bundle/chainlink.json
js/pint-types-bundle/index.ts
js/pint-types-bundle/tsconfig.json

```
2021-06-17 16:02:12        REGISTRY: Unable to resolve type ProposalNonce, it will fail on construction
2021-06-17 16:02:12        METADATA: Unknown types found, no types for FeedIdFor, PendingRedemption, ProposalNonce, SAFTRecord
```
Closes #110

feat(js): complete PINT types

---

Cargo.lock
node/src/cli.rs

- remove `conflict_with` in ExportGenesisStateCommand
```
CI
```
Closes #127

chore(cli): remove conflict check in ExportGenesisStateCommand

---

Cargo.lock
js/e2e/index.ts
js/e2e/src/runner.ts
js/pint-types-bundle/index.ts
node/Cargo.toml
node/src/chain_spec.rs
pallets/remote-asset-manager/src/lib.rs
runtime/src/lib.rs

E2E tests for pallet remote asset manager

---

README.md
node/src/chain_spec.rs
resources/types.json

- update run desc
- Ref #151  
- Ref #169

chore: add run description and types

---

Cargo.lock
config.json
js/e2e/index.ts
js/e2e/package.json
js/e2e/src/runner.ts
js/e2e/src/util.ts
js/finalize/index.ts
js/pint-types-bundle/index.ts
js/yarn.lock
pallets/price-feed/src/lib.rs

- Add API tests for 
- Display transaction errors
- Pend errors in queue
```
CI
```
Ref https://github.com/open-web3-stack/open-runtime-module-library/issues/499
Ref #81  
Ref #147
Cloeses #170 #176 #177 #178 #180

feat(e2e): pend and display errors in e2e tests

---

pallets/remote-asset-manager/src/lib.rs
primitives/xcm-calls/src/staking.rs

- Adds 2 more extrinsics to update the configured weights for staking/proxy for the given asset
```
```
- Closes #199

feat: add update functions for xcm calls

---

Cargo.lock
Cargo.toml
runtime/src/lib.rs

- Add support for new `BaseXcmWeight` type
```
```
-

chore(deps): update orml

---

Cargo.lock
Cargo.toml
node/Cargo.toml
node/src/service.rs
pallets/asset-index/Cargo.toml
pallets/committee/Cargo.toml
pallets/committee/src/lib.rs
pallets/local-treasury/Cargo.toml
pallets/price-feed/Cargo.toml
pallets/remote-asset-manager/Cargo.toml
pallets/saft-registry/Cargo.toml
primitives/primitives/Cargo.toml
primitives/xcm-calls/Cargo.toml
runtime/Cargo.toml
runtime/src/lib.rs
test-utils/xcm-test-support/Cargo.toml

- update polkadot 0.9.8
```
cargo t
```
-

chore(deps): update upstream dependencies

---

Cargo.lock
pallets/price-feed/Cargo.toml
pallets/price-feed/src/lib.rs
pallets/price-feed/src/mock.rs
pallets/price-feed/src/types.rs
runtime/common/Cargo.toml
runtime/dev/Cargo.toml
runtime/dev/src/lib.rs
runtime/kusama/Cargo.toml
runtime/kusama/src/lib.rs
runtime/polkadot/Cargo.toml
runtime/polkadot/src/lib.rs

- use trait `chainlink::Config` trait bound instead of `Oracle` type
- timestamp answers
```
cargo t
```
- Closes #246

perf: simplify price feed pallet

---

node/src/client.rs
pallets/asset-index/src/benchmarking.rs
pallets/asset-index/src/lib.rs
pallets/asset-index/src/mock.rs
pallets/committee/src/lib.rs
pallets/committee/src/tests.rs
pallets/local-treasury/src/mock.rs
pallets/price-feed/src/lib.rs
pallets/price-feed/src/tests.rs
pallets/remote-asset-manager/src/lib.rs
pallets/remote-asset-manager/src/mock.rs
pallets/remote-asset-manager/src/tests.rs
pallets/saft-registry/src/lib.rs
pallets/saft-registry/src/tests.rs
primitives/xcm-calls/src/lib.rs
primitives/xcm-calls/src/staking.rs
runtime/common/src/constants.rs
runtime/dev/src/lib.rs
runtime/kusama/src/lib.rs
runtime/polkadot/src/lib.rs
test-utils/xcm-test-support/src/lib.rs

- run rustfmt on whole code base
Will also open an issue to add rustfmt.toml to the repo.
```
```
-

style(rustfmt):  imports_granularity=Crate && wrap_comments=true 

---

Cargo.lock
pallets/asset-index/Cargo.toml
pallets/asset-index/src/benchmarking.rs
pallets/asset-index/src/lib.rs
pallets/asset-index/src/mock.rs
pallets/asset-index/src/tests.rs
pallets/asset-index/src/types.rs
pallets/price-feed/src/benchmarking.rs
pallets/price-feed/src/lib.rs
pallets/price-feed/src/mock.rs
pallets/price-feed/src/tests.rs
pallets/price-feed/src/traits.rs
pallets/remote-asset-manager/src/mock.rs
pallets/remote-asset-manager/src/tests.rs
pallets/saft-registry/src/mock.rs
primitives/primitives/src/traits.rs
primitives/primitives/src/types.rs
runtime/common/src/weights/pallet_price_feed.rs

- fixed all proportion and redemption math
- extend `NavProvider` with proportion calculation
- add more docs for provider trait
```
```
- Closes #252 
- Ref #237

feat: simplify price feeds and redemption process

---

js/e2e/index.ts
js/e2e/src/extrinsic.ts
js/e2e/src/runner.ts
js/pint-types-bundle/index.ts

-
```
CI
```
- #256
- Closes #267
- Closes #279

feat(e2e): Complete js types and fix e2e tests

---

js/e2e/index.ts
js/pint-types-bundle/index.ts

waiting after withdrawals period in the test of `complete_withdrawal
```
CI
```
- Closes #280

feat(e2e): adds WithdrawalsPeriod for the complete_withdraw call

---

js/e2e/index.ts
js/pint-types-bundle/index.ts
pallets/remote-asset-manager/src/types.rs

- fix the verification part of pallet-remote-asset
```
CI
```
- Closes #285

feat(e2e): updates the verification part of pallet remote-asset-manager

---

pallets/asset-index/src/lib.rs
pallets/remote-asset-manager/src/tests.rs

feat(asset-index): mint asset into the treasury account in add_asset call

---

js/pint-types-bundle/index.ts
pallets/remote-asset-manager/src/lib.rs
pallets/remote-asset-manager/src/mock.rs
pallets/remote-asset-manager/src/tests.rs
pallets/remote-asset-manager/src/types.rs
runtime/common/src/constants.rs
runtime/dev/src/lib.rs
runtime/kusama/src/lib.rs
runtime/polkadot/src/lib.rs
test-utils/xcm-test-support/src/lib.rs

- No more Xcm Transact when interacting with statemint
- uses native xcm withdraw/deposit scheme when interacting with statemint and drop xcm assets transact support
- dedicated support for transferring tokens to statemint
Disabled the statemint test that requires an update to latest 0.9.9
```
```
- Ref #234

feat: update statemint xcm support

---

.github/workflows/check-licence.yml

- use go v1.16
-
-
```
```
- Closes #289

ci(header): fix check-license

---

pallets/asset-index/src/lib.rs
runtime/common/src/weights/pallet_asset_index.rs

- complete weights attributes for all calls
```
CI
```
- Closes #283

chore(asset-index): extend weights for pallet asset-index

---

.circleci/config.yml

chore(ci): test all crates but all-features only for dev runtime

---

Cargo.lock
Cargo.toml
pallets/asset-index/src/benchmarking.rs
pallets/asset-index/src/lib.rs
pallets/asset-index/src/mock.rs
pallets/price-feed/src/benchmarking.rs
pallets/price-feed/src/lib.rs
pallets/price-feed/src/traits.rs
pallets/remote-asset-manager/src/lib.rs
pallets/remote-asset-manager/src/mock.rs
pallets/saft-registry/src/benchmarking.rs
pallets/saft-registry/src/lib.rs
pallets/saft-registry/src/mock.rs

- This eases the creation of AssetIds in benchmarks and makes it compatible with Acala aswell
```
```
-

fix: remove some AssetId bounds and add TryFrom<u8>

---

.circleci/config.yml
Cargo.lock
Cargo.toml
node/Cargo.toml

- remove `polkadot-test-service`
- update CI
```
CI
```
- Closes #311

feat(node): remove polkadot-test-service

---

runtime/dev/src/lib.rs
runtime/kusama/src/lib.rs
runtime/polkadot/src/lib.rs

- list benchmarks for all runtimes
```
CI
```
- Closes #314

feat(runtime): list benchmarks for all runtimes

---

pallets/local-treasury/src/lib.rs

chore: typos and docs

---

pallets/asset-index/src/mock.rs
pallets/saft-registry/src/mock.rs
primitives/primitives/src/traits.rs

- Add a default implementation for remote asset manager that does nothing
```
```
-

feat: add default remote asset manager impl

---

node/src/service.rs
pallets/asset-index/src/lib.rs
pallets/asset-index/src/mock.rs
pallets/asset-index/src/tests.rs
pallets/remote-asset-manager/src/mock.rs
pallets/saft-registry/src/mock.rs
primitives/primitives/src/traits.rs
runtime/common/src/constants.rs
runtime/dev/src/lib.rs
runtime/kusama/src/lib.rs
runtime/polkadot/src/lib.rs

feat(asset-index): timestamp deposits

---

Cargo.lock
pallets/local-treasury/src/lib.rs
pallets/remote-treasury/Cargo.toml
pallets/remote-treasury/README.md
pallets/remote-treasury/src/lib.rs

- Adds remote treasury pallet to transfer funds from the treasury to an account of the asset's chain.
Will follow up with more sophisticated XCM tests
- Closes #272

feat: add xcm remote treasury pallet

---

pallets/asset-index/Cargo.toml
pallets/asset-index/src/benchmarking.rs
pallets/asset-index/src/lib.rs
pallets/asset-index/src/mock.rs
pallets/asset-index/src/tests.rs
pallets/asset-index/src/types.rs
pallets/remote-asset-manager/src/mock.rs
pallets/saft-registry/src/mock.rs
resources/types.json
runtime/common/src/constants.rs
runtime/common/src/weights/pallet_asset_index.rs
runtime/dev/src/lib.rs
runtime/kusama/src/lib.rs
runtime/polkadot/src/lib.rs

- Add a configurable range for valid deposits
```
```
- Closes #271

feat: add index token deposit range

---

Cargo.lock
docs/usage/configuration.md
node/src/chain_spec/dev.rs
node/src/chain_spec/kusama.rs
node/src/chain_spec/polkadot.rs
pallets/asset-index/Cargo.toml
pallets/price-feed/Cargo.toml
pallets/price-feed/src/mock.rs
runtime/common/Cargo.toml
runtime/dev/Cargo.toml
runtime/kusama/Cargo.toml
runtime/polkadot/Cargo.toml

chore: upgrade chainlink pallet

---

pallets/asset-index/src/lib.rs
pallets/committee/src/lib.rs
pallets/local-treasury/src/lib.rs
pallets/saft-registry/src/lib.rs

- add more docs in pallets and unify some syntax and error types
```
```
-

chore(docs): add more pallet docs

---

README.md

chore(docs): update nightly version to match CI

---

pallets/asset-index/src/lib.rs

- Use same conversion logic when removing SAFT
```
```
- Closes #349

fix: determine the index token euqivalent when removing a saft

---

js/e2e/index.ts
js/e2e/src/config.ts
js/e2e/src/extrinsic.ts
js/e2e/src/runner.ts
js/pint-types-bundle/index.ts
runtime/dev/src/lib.rs

Supports wrapping txs as proposals and queue them
```
CI
```
- Ref #301 
- Closes #352 
- Closes #357

feat(e2e): add shortcut for proposing extrinsic

---

node/src/chain_spec/dev.rs
node/src/chain_spec/kusama.rs
node/src/chain_spec/polkadot.rs
pallets/remote-asset-manager/src/lib.rs
pallets/remote-asset-manager/src/mock.rs
primitives/xcm-calls/src/staking.rs
runtime/common/src/weights/pallet_remote_asset_manager.rs

- Add freeze and thaw functions to halt/continue xcm transfers and staking
```
```
- Closes #290

feat: add freeze and thaw extrinsics

---

js/e2e/src/extrinsic.ts
js/pint-types-bundle/index.ts
pallets/committee/src/benchmarking.rs
pallets/committee/src/lib.rs
pallets/committee/src/tests.rs
pallets/committee/src/types.rs
resources/types.json

- Rename `Vote` --> `VoteKind`
- update usages in JS and types.json
```
```
- Closes #377

fix: rename Vote type

---

pallets/asset-index/src/lib.rs
pallets/asset-index/src/tests.rs

- Ensures metadata is not empty
```
```
- Closes #362

fix: ensure non empty metadata

---

Cargo.lock
pallets/committee/Cargo.toml
pallets/committee/src/lib.rs

- Log error match arm for upkeep
- Calculate weight for `upkeep` by hand
```
```
- Closes #370

feat: determine weight for upkeep and log error case

---

pallets/remote-treasury/src/lib.rs

- Will transfers of amount zero would be caught down the line in the `XcmTransfer` implementation. We should nevertheless check for it and short circuit.
```
```
- Closes #364

fix: make zero amount transfers noops

---

.circleci/config.yml
pallets/asset-index/src/benchmarking.rs
pallets/asset-index/src/lib.rs
pallets/saft-registry/src/benchmarking.rs
primitives/primitives/src/traits.rs

- test generating weights in CI
```
CI
```
- Closes #351

feat(ci): test benchmarks in CI

---

pallets/asset-index/src/lib.rs
pallets/asset-index/src/mock.rs
pallets/asset-index/src/tests.rs
pallets/remote-asset-manager/src/mock.rs
pallets/saft-registry/src/mock.rs
runtime/common/src/constants.rs
runtime/dev/src/lib.rs
runtime/kusama/src/lib.rs
runtime/polkadot/src/lib.rs

- introduce `MaxDecimals`
```
CI
```
- Closes #363

feat(asset-index): add check for decimals of asset metadata

---

docs/getting-started/overview/architecture.md

- use correct relative path for nav formula png
```
```
-

fix: relative img path

---

config.json
docker/launch.Dockerfile
js/e2e/src/launch.ts
package-lock.json

chore(launch): update polkadot launch with bug fixes

---

pallets/committee/src/lib.rs

feat(weight): update dispatch class for important calls

---

pallets/asset-index/src/lib.rs
pallets/committee/src/lib.rs
pallets/price-feed/src/lib.rs
pallets/remote-asset-manager/src/lib.rs
primitives/primitives/src/traits.rs

- Fix tests
- make clippy happy
```
ci
```
- Closes #401

chore(tests): patch #401

---

pallets/saft-registry/src/lib.rs

feat: include SaftRecord in events

---

pallets/committee/src/lib.rs
pallets/committee/src/tests.rs

- introduce storage `VotingTimeouts`
- insert new members in to `VotingTimeouts`
- check and clean timeouts on voting
- tests for `MemberNotInVotingPeriod`
```
CI
```
- Closes #373

feat(committee): introduce storage VotingTimeouts

---

js/pint-types-bundle/index.ts
pallets/committee/src/benchmarking.rs
pallets/committee/src/lib.rs
pallets/committee/src/mock.rs
pallets/committee/src/tests.rs
pallets/committee/src/types.rs
resources/types.json

```
CI
```
- Closes #408
- Closes #393

feat(committee): refactor Proposal and add timeout

---

pallets/committee/src/lib.rs
pallets/committee/src/tests.rs

-
-
-
```
CI
```
- Closes #418

feat(committee): testing new members cannot vote

---

pallets/committee/src/lib.rs
pallets/committee/src/mock.rs
pallets/committee/src/tests.rs
pallets/committee/src/traits.rs
runtime/common/src/types.rs
runtime/dev/src/lib.rs
runtime/kusama/src/lib.rs
runtime/polkadot/src/lib.rs

- use `VotingPeriodRange` and remove `Days` in the config of pallet committee
- updates initial VotingPeriod
-
```
CI
```
- Closes #428

feat(committee): introduce VotingPeriodRange

---

Cargo.lock
node/Cargo.toml
pallets/asset-index/Cargo.toml
pallets/asset-index/rpc/Cargo.toml
pallets/asset-index/rpc/runtime-api/Cargo.toml
pallets/local-treasury/Cargo.toml
pallets/price-feed/Cargo.toml
pallets/remote-asset-manager/Cargo.toml
pallets/remote-treasury/Cargo.toml
pallets/saft-registry/Cargo.toml
primitives/derive/Cargo.toml
primitives/primitives/Cargo.toml
primitives/xcm-calls/Cargo.toml
runtime/common/Cargo.toml
runtime/dev/Cargo.toml
runtime/integration-tests/Cargo.toml
runtime/kusama/Cargo.toml
runtime/polkadot/Cargo.toml

- cargo upgrade --workspace
-
-
```
```
-

chore(cargo): cargo upgrade

---

pallets/committee/src/lib.rs

- use dispatch weight and typos
```
```
-

chore: add dispatch weight
